### ISSUE TITLE
Akali与Sentinel

### ISSUE THREAD

**Issue by Wow-wang** [bryan31/Akali#1]
作者大大，为啥不直接使用Sentinel，相比之下Akali优势在哪？

**Comment by bryan31** [comment]
Akali底层的确使用了sentinel的资源控制。
Akali本身就是一个小框架，sentinel底层的资源控制只是基础能力，但是sentinel核心的资源控制只是基于代码层面的。Akali扩展了sentinel的能力，使得更加容易方便的使用，只需要加标注而不需要侵入业务代码。并且针对了2个独特的场景进行了封装。
框架的意义就是让接入者更加方便的使用，而不用去关心底层的细节。
